call mvn install:install-file -DgroupId=com.blackbook -DartifactId=BBCarTruckAPI -Dversion=2.0.4 -Dpackaging=jar -Dfile=BBCarTruckAPI.jar
call mvn install:install-file -DgroupId=com.ibm.websphere -DartifactId=commonj -Dversion=7.0 -Dpackaging=jar -Dfile=com.ibm.ws.prereq.commonj-twm.jar
call mvn install:install-file -DgroupId=com.ibm.websphere -DartifactId=wsdl4j -Dversion=7.0 -Dpackaging=jar -Dfile=com.ibm.ws.prereq.wsdl4j.jar
call mvn install:install-file -DgroupId=com.ibm.websphere -DartifactId=runtime -Dversion=7.0 -Dpackaging=jar -Dfile=com.ibm.ws.runtime.jar
call mvn install:install-file -DgroupId=com.ibm.websphere -DartifactId=ibmpkcs -Dversion=7.0 -Dpackaging=jar -Dfile=ibmpkcs.jar
call mvn install:install-file -DgroupId=com.ibm.websphere -DartifactId=admin-core -Dversion=7.0 -Dpackaging=jar -Dfile=com.ibm.ws.admin.core.jar
call mvn install:install-file -DgroupId=com.oracle -DartifactId=ojdbc14 -Dversion=10.2.0.1 -Dpackaging=jar -Dfile=ojdbc14.jar
call mvn install:install-file -DgroupId=javapns -DartifactId=javapns -Dversion=2.2 -Dpackaging=jar -Dfile=JavaPNS_2.2.jar
call mvn install:install-file -DgroupId=org.richfaces -DartifactId=richfaces-ui -Dversion=3.1.1-GA -Dpackaging=jar -Dfile=richfaces-ui-3.1.1-GA.jar
call mvn install:install-file -DgroupId=org.richfaces -DartifactId=richfaces-api -Dversion=3.1.1-GA -Dpackaging=jar -Dfile=richfaces-api-3.1.1-GA.jar
call mvn install:install-file -DgroupId=org.richfaces -DartifactId=richfaces-impl -Dversion=3.1.1-GA -Dpackaging=jar -Dfile=richfaces-impl-3.1.1-GA.jar
call mvn install:install-file -DgroupId=com.exadel.htmLib -DartifactId=htmLib -Dversion=0.0.1 -Dpackaging=jar -Dfile=htmLib.jar
call mvn install:install-file -DgroupId=jaxb-api -DartifactId=jaxb-api -Dversion=1.0.2 -Dpackaging=jar -Dfile=jaxb-api.jar
call mvn install:install-file -DgroupId=jaxb-impl -DartifactId=jaxb-impl -Dversion=1.0.2 -Dpackaging=jar -Dfile=jaxb-impl.jar
call mvn install:install-file -DgroupId=jaxb-libs -DartifactId=jaxb-libs -Dversion=20031010 -Dpackaging=jar -Dfile=jaxb-libs.jar
call mvn install:install-file -DgroupId=relaxngDatatype -DartifactId=relaxngDatatype -Dversion=0.0.1 -Dpackaging=jar -Dfile=relaxngDatatype.jar
call mvn install:install-file -DgroupId=commons-util -DartifactId=commons-util -Dversion=0.0.1 -Dpackaging=jar -Dfile=commons-util.jar
call mvn install:install-file -DgroupId=commons-mail -DartifactId=commons-mail -Dversion=0.0.1 -Dpackaging=jar -Dfile=commons-mail.jar
call mvn install:install-file -DgroupId=JimiProClasses -DartifactId=JimiProClasses -Dversion=0.0.1 -Dpackaging=jar -Dfile=JimiProClasses.jar
call mvn install:install-file -DgroupId=javax.mail -DartifactId=mail -Dversion=1.2 -Dpackaging=jar -Dfile=mail.jar
call mvn install:install-file -DgroupId=com.ostermiller -DartifactId=utils -Dversion=1.05.00 -Dpackaging=jar -Dfile=ostermillerutils_1_05_00_for_java_1_4.jar
call mvn install:install-file -DgroupId=org.opensymphony.quartz -DartifactId=quartz -Dversion=1.6.5 -Dpackaging=jar -Dfile=quartz-1.6.5.jar
call mvn install:install-file -DgroupId=json4j -DartifactId=json4j -Dversion=0.0.1 -Dpackaging=jar -Dfile=JSON4J.jar